name: Our Hardened Pipeline (Comparison)

on:
  push:
    branches: [ free-devsecops-pipeline ]
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  pages: write
  id-token: write

jobs:
  security-scan:
    uses: ananthu3212/shift-left-security-thesis/.github/workflows/security-scan-reusable.yml@main
    with:
      docker-image-name: pygoat-comparison
      semgrep-config: p/python
      enable-flask-rules: false
      enable-dast: false
      trivy-severity: HIGH,CRITICAL
      fail-on-findings: false
    secrets: inherit
    #ss